### ISSUE TITLE
Error: Unable to bind

### ISSUE THREAD

**Issue by 0323pin** [igor-petruk/oatbar#6]
Hi,

I've tried `oatbar` a few months ago and was able to launch it. Today, I've decided to give it another try, given the latest progress of the project.

I've created a NetBSD package, built and installed it but, it fails to launch with:

```
2023-11-24T08:15:00.732931Z  WARN main oatbar::config: Config at "/home/pin/.config/oatbar.toml" is missing. Writing default config...
2023-11-24T08:15:00.736200Z  INFO main oatbar::wmready: Debug: wm_support=Atom { res_id: 283 }, wm_name=Atom { res_id: 284 }, wm_net_supported=Atom { res_id: 293 }
2023-11-24T08:15:00.742180Z  INFO main oatbar::wmready: Supported EWMH: GetPropertyReply { response_type: 1, format: 32, sequence: 8, length: 22, r#type: Atom { res_id: 4 }, bytes_after: 0, value_len: 22, pad: 12, value: [286, 287, 288, 289, 290, 291, 292, 293, 283, 294, 284, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305] }
2023-11-24T08:15:00.742234Z  INFO main oatbar::wmready: Detected WM: "marswm"
2023-11-24T08:15:00.745005Z  INFO main oatbar::engine: XInput init: XiQueryVersionReply { response_type: 1, pad: 1, sequence: 10, length: 0, major_version: 2, minor_version: 0, pad: 20 }
2023-11-24T08:15:00.745089Z  INFO main oatbar::window: Loading bar "bar0"
2023-11-24T08:15:00.745122Z  INFO main oatbar::xrandr: Trying to find the primary monitor.
2023-11-24T08:15:00.745325Z  INFO main oatbar::xrandr: Detected Monitor { name: "eDP1", primary: true, x: 0, y: 0, width: 1366, height: 768 }
2023-11-24T08:15:00.745362Z  INFO main oatbar::xrandr: Monitor found: eDP1
2023-11-24T08:15:00.745489Z  INFO main oatbar::window: Placing the bar at x: 0, y: 736, width: 1366, height: 32
Error: Unable to bind

Caused by:
    No such file or directory (os error 2)
Exception: oatbar exited with 1
[tty 1]:1:1: oatbar
thread 'main' panicked at library/std/src/io/stdio.rs:1019:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at library/std/src/io/stdio.rs:1019:9:
failed printing to stdout: Broken pipe (os error 32)
```

Any pointers?
Thanks

**Comment by igor-petruk** [comment]
Sorry for the issue. I've released 0.0.26 with the fix, can you please try.

**Comment by igor-petruk** [comment]
Also, given a bit change since yesterday, the default config might not show disk and clock (I just realized), I'll try to fix it quickly

**Comment by 0323pin** [comment]
Will have to build 0.0.27 than. But, yes the issue with _Unable to bind_ is fixed in 0.0.26.
![2023-11-24-104651_1366x768_scrot](https://github.com/igor-petruk/oatbar/assets/90570748/9371c7a2-a7ef-4202-963a-ca70d0771d69)

I'll update to 0.0.27 and merge the package into pkgsrc main branch.

Interested in install instructions on NetBSD for your homepage?

**Comment by igor-petruk** [comment]
> Interested in install instructions on NetBSD for your homepage?

Yes, absolutely, that'd be great 👍

Thank you for reporting the bug. I am actively working on finishing all small things and writing a proper documentation so I can announce the bar on a few resources, so every improvement counts

**Comment by 0323pin** [comment]
@igor-petruk Merged into main, http://mail-index.netbsd.org/pkgsrc-changes/2023/11/24/msg287606.html

**Comment by igor-petruk** [comment]
Thank you very much!

**Comment by 0323pin** [comment]
You're welcome.

**Comment by 0323pin** [comment]
@igor-petruk Been playing around with `oatbar` for a few minutes now and the fist thing I'm missing is how to configure fonts and font-size. Is this possible?

**Comment by igor-petruk** [comment]
There are two ways: font property of the block and Pango markup.

https://docs.gtk.org/Pango/pango_markup.html

Pango markup is more verbose, but it let's your control parts of the text, not only the entire block

**Comment by igor-petruk** [comment]
Also, the documentation is coming, I will document everything very well. At the moment I think customization capabilities are already incredible, I've been using the bar myself for very long time, but only now I am trying to make it usable for everyone.

Happy to answer any questions meanwhile

**Comment by 0323pin** [comment]
Thank you! I'll let you know if I find anything else missing 😃 

> This bar aims to become one of the most full-featured bars available.

**Comment by 0323pin** [comment]
Btw, I'll suggest `oatbar` for LeftWM 😉

**Comment by igor-petruk** [comment]
I've been using with LeftWM at home, i3 at work. I'ved testing it now with cwm, as my main development system is OpenBSD.

They all behave differently, so it helps to discover bugs.

Since the strong selling point of the bar is being able to ingest data from plugins from other ecosystems, I feed i3status via i3bar protocol to get a lot of data, plus some custom scripts

**Comment by 0323pin** [comment]
This is exactly what I was thinking, piping `leftwm-status` into it and have a default config available. I've suggested it internally now.

![2023-11-24-134953_1366x768_scrot](https://github.com/igor-petruk/oatbar/assets/90570748/03727015-0e99-4846-a5ec-bcad561a63f2)

In the screenshot is `marsbar`, though as it comes with the WM I'm using on NetBSD, `marswm`. I have LeftWM on Void Linux.

**Comment by igor-petruk** [comment]
Oh, thank you very much 😊

My only concern is the stability of configs. 1) they may change unexpectedly because it is 0.0.x; 2) I am not entirely happy how they are parsed in Rust, so at some point I'll be seeking the advice from the community if the current system makes sense and if we need to do it differently.

So yeah, thanks for suggesting, but it is also a very early stage project and people should be aware of that fact 😁

**Comment by igor-petruk** [comment]
FYI, I've also implemented https://github.com/igor-petruk/scriptisto, which is very stable. The cool part is that it can be used to write simple one file scripts for `oatbar` in Rust (or C, or whatever) and then saving on resources because the script is "native"
